{"name": "test_05_negative_signin_with_username", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_logins.TestBestInTownPizzaLogin testMethod=test_05_negative_signin_with_username>\n\n    def setUp(self):\n    \n        # chrome_options = Options()\n        # chrome_options.add_argument(\"--headless\")\n        # self.driver = webdriver.Chrome(executable_path=\"C:/Users/Administrator/Desktop/BEST_IN_TOWN/chromedriver.exe\", options=chrome_options)\n    \n        self.driver = webdriver.Chrome(\n            \"C:/Users/Digital Suppliers/Desktop/bestintown/chromedriver.exe\")\n    \n        f = open('data.json', \"r\")\n        data = json.loads(f.read())\n>       fetching_website(self.driver, data[\"url\"])\n\ntest_logins.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmethods.py:31: in fetching_website\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f6e9417c49f6ef34dd43fa88f594ddba\")>, site_url = 'http://bestintownpizzas.com/home'\n\n    @allure.step(\"To fetch the website with url: {1}\")\n    def fetching_website(driver, site_url):\n        try:\n            driver.get(site_url)\n            # driver.maximize_window()\n            driver.set_window_size(1536, 864)\n            driver.implicitly_wait(5)\n            print(driver.title)\n            allure.attach(driver.get_screenshot_as_png(),\n                          name='website_screen', attachment_type=AttachmentType.PNG)\n    \n            driver.find_element_by_id(loginlocators.start_button).click()\n>           assert driver.title == \"Home | Best In Town Pizza\"\nE           AssertionError\n\nmethods.py:28: AssertionError"}, "description": "To verify on entering incorrect login username, correct error message is displaying.", "steps": [{"name": "To fetch the website with url: 'http://bestintownpizzas.com/home'", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Digital Suppliers\\Desktop\\bestintown\\methods.py\", line 31, in fetching_website\n    raise e\n  File \"C:\\Users\\Digital Suppliers\\Desktop\\bestintown\\methods.py\", line 28, in fetching_website\n    assert driver.title == \"Home | Best In Town Pizza\"\n"}, "attachments": [{"name": "website_screen", "source": "a852776d-24c3-4101-8a1d-0e7bb56d2bb7-attachment.png", "type": "image/png"}], "parameters": [{"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"f6e9417c49f6ef34dd43fa88f594ddba\")>"}, {"name": "site_url", "value": "'http://bestintownpizzas.com/home'"}], "start": 1666871298362, "stop": 1666871309331}], "start": 1666871296710, "stop": 1666871309332, "uuid": "a05c4acf-ea43-4ae8-bc83-7d24237aade8", "historyId": "ac1bc179800687008cdef005bd4766d0", "testCaseId": "841a1c5ba2a05c960802132c9476c807", "fullName": "test_logins.TestBestInTownPizzaLogin#test_05_negative_signin_with_username", "labels": [{"name": "suite", "value": "test_logins"}, {"name": "subSuite", "value": "TestBestInTownPizzaLogin"}, {"name": "host", "value": "DESKTOP-JHQBC5Q"}, {"name": "thread", "value": "9640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_logins"}]}