{"name": "test_02_negative_signin", "status": "broken", "statusDetails": {"message": "NameError: name 'error2' is not defined", "trace": "self = <test_logins.TestBestInTownPizzaLogin testMethod=test_02_negative_signin>\n\n    @allure.description(\"To verify on entering incorrect login details, correct error message is displaying.\")\n    def test_02_negative_signin(self):\n        By_xpath = self.driver.find_element_by_xpath\n        try:\n            f = open(\"data.json\", \"r\")\n            data = json.loads(f.read())\n            time.sleep(5)\n            invalid_signin(self.driver, data[\"username\"], \"abc1234\")\n            print(\"Test 02 ran successfully\")\n            f.close()\n        except Exception as e:\n            allure.attach(self.driver.get_screenshot_as_png(\n            ), name='exception_screen', attachment_type=AttachmentType.PNG)\n>           raise e\n\ntest_logins.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntest_logins.py:68: in test_02_negative_signin\n    invalid_signin(self.driver, data[\"username\"], \"abc1234\")\nmethods.py:360: in invalid_signin\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"cfd119040725eeceda2b41e04e307cb6\")>, email = 'devsharktank@gmail.com', password = 'abc1234'\n\n    @allure.step(\"To verify that user is able to sign in withwrong credientials\")\n    def invalid_signin(driver, email, password):\n        By_xpath = driver.find_element_by_xpath\n        By_id = driver.find_element_by_id\n        try:\n            By_xpath(loginlocators.home_signin_btn).click()\n            time.sleep(1)\n            By_id(loginlocators.signin_email).send_keys(email)\n            By_id(loginlocators.signin_password).send_keys(password)\n            By_xpath(loginlocators.signin_btn).click()\n            time.sleep(1)\n            error = By_xpath(loginlocators.incorrect_msg).text\n            allure.attach(driver.get_screenshot_as_png(),\n                          name='Signin_screen', attachment_type=AttachmentType.PNG)\n>           print(error2)\nE           NameError: name 'error2' is not defined\n\nmethods.py:355: NameError"}, "description": "To verify on entering incorrect login details, correct error message is displaying.", "steps": [{"name": "To fetch the website with url: 'http://bestintownpizzas.com/home'", "status": "passed", "attachments": [{"name": "website_screen", "source": "cffe3bf9-6fb7-45a7-94a1-36eb39ff742a-attachment.png", "type": "image/png"}], "parameters": [{"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"cfd119040725eeceda2b41e04e307cb6\")>"}, {"name": "site_url", "value": "'http://bestintownpizzas.com/home'"}], "start": 1666872402873, "stop": 1666872417552}, {"name": "To verify that user is able to sign in withwrong credientials", "status": "broken", "statusDetails": {"message": "NameError: name 'error2' is not defined\n", "trace": "  File \"c:\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Digital Suppliers\\Desktop\\bestintown\\methods.py\", line 360, in invalid_signin\n    raise e\n  File \"C:\\Users\\Digital Suppliers\\Desktop\\bestintown\\methods.py\", line 355, in invalid_signin\n    print(error2)\n"}, "attachments": [{"name": "Signin_screen", "source": "1968878f-f330-436c-b213-2508e4a4b495-attachment.png", "type": "image/png"}], "parameters": [{"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"cfd119040725eeceda2b41e04e307cb6\")>"}, {"name": "email", "value": "'devsharktank@gmail.com'"}, {"name": "password", "value": "'abc1234'"}], "start": 1666872422553, "stop": 1666872427416}], "attachments": [{"name": "exception_screen", "source": "0d5c47f1-6363-43c3-9e93-67ce97db41af-attachment.png", "type": "image/png"}], "start": 1666872401476, "stop": 1666872429892, "uuid": "b7dc4a25-2763-4e5a-aa16-7b4e53b52a12", "historyId": "2e859936d4a7235097276008a90e659d", "testCaseId": "ac5cc146185c8c0b6cb1e2d9f265ca6d", "fullName": "test_logins.TestBestInTownPizzaLogin#test_02_negative_signin", "labels": [{"name": "suite", "value": "test_logins"}, {"name": "subSuite", "value": "TestBestInTownPizzaLogin"}, {"name": "host", "value": "DESKTOP-JHQBC5Q"}, {"name": "thread", "value": "8044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_logins"}]}