{"name": "test_02_negative_signin", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'loginlocators' has no attribute 'incorrect_msg'", "trace": "self = <test_logins.TestBestInTownPizzaLogin testMethod=test_02_negative_signin>\n\n    @allure.description(\"To verify on entering incorrect login details, correct error message is displaying.\")\n    def test_02_negative_signin(self):\n        By_xpath = self.driver.find_element_by_xpath\n        try:\n            f = open(\"data.json\", \"r\")\n            data = json.loads(f.read())\n            time.sleep(5)\n            invalid_signin(self.driver, data[\"username\"], \"abc1234\")\n            print(\"Test 02 ran successfully\")\n            f.close()\n        except Exception as e:\n            allure.attach(self.driver.get_screenshot_as_png(\n            ), name='exception_screen', attachment_type=AttachmentType.PNG)\n>           raise e\n\ntest_logins.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntest_logins.py:63: in test_02_negative_signin\n    invalid_signin(self.driver, data[\"username\"], \"abc1234\")\nmethods.py:329: in invalid_signin\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc61a24b83e3ad1094ccf42d4fc70623\")>, email = 'devsharktank@gmail.com', password = 'abc1234'\n\n    @allure.step(\"To verify that user is able to sign in withwrong credientials\")\n    def invalid_signin(driver, email, password):\n        By_xpath = driver.find_element_by_xpath\n        By_id = driver.find_element_by_id\n        try:\n            By_xpath(loginlocators.home_signin_btn).click()\n            time.sleep(1)\n            By_id(loginlocators.signin_email).send_keys(email)\n            By_id(loginlocators.signin_password).send_keys(password)\n            By_xpath(loginlocators.signin_btn).click()\n            time.sleep(1)\n>           error = By_xpath(loginlocators.incorrect_msg).text\nE           AttributeError: type object 'loginlocators' has no attribute 'incorrect_msg'\n\nmethods.py:321: AttributeError"}, "description": "To verify on entering incorrect login details, correct error message is displaying.", "steps": [{"name": "To fetch the website with url: 'http://bestintownpizzas.com/home'", "status": "passed", "attachments": [{"name": "website_screen", "source": "8ccab7e3-9189-4c26-943d-53c4acc424ee-attachment.png", "type": "image/png"}], "parameters": [{"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc61a24b83e3ad1094ccf42d4fc70623\")>"}, {"name": "site_url", "value": "'http://bestintownpizzas.com/home'"}], "start": 1668490478747, "stop": 1668490488945}, {"name": "To verify that user is able to sign in withwrong credientials", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'loginlocators' has no attribute 'incorrect_msg'\n", "trace": "  File \"c:\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Digital Suppliers\\Desktop\\bestintown\\methods.py\", line 329, in invalid_signin\n    raise e\n  File \"C:\\Users\\Digital Suppliers\\Desktop\\bestintown\\methods.py\", line 321, in invalid_signin\n    error = By_xpath(loginlocators.incorrect_msg).text\n"}, "parameters": [{"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"bc61a24b83e3ad1094ccf42d4fc70623\")>"}, {"name": "email", "value": "'devsharktank@gmail.com'"}, {"name": "password", "value": "'abc1234'"}], "start": 1668490493949, "stop": 1668490498750}], "attachments": [{"name": "exception_screen", "source": "efd3535b-e083-4250-a520-46b34cfda666-attachment.png", "type": "image/png"}], "start": 1668490477188, "stop": 1668490501313, "uuid": "e358bc81-5324-462d-b320-9c479adf5767", "historyId": "2e859936d4a7235097276008a90e659d", "testCaseId": "ac5cc146185c8c0b6cb1e2d9f265ca6d", "fullName": "test_logins.TestBestInTownPizzaLogin#test_02_negative_signin", "labels": [{"name": "suite", "value": "test_logins"}, {"name": "subSuite", "value": "TestBestInTownPizzaLogin"}, {"name": "host", "value": "DESKTOP-JHQBC5Q"}, {"name": "thread", "value": "11116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_logins"}]}